schema_version = "1.1.0"

id = "focus_on_selected_gui"
name = "Focus on Selected (GUI)"
tagline = "Frame/reveal selected objects button in Viewport and Outliner"
version = "1.0.0"
type = "add-on"

tags = ["User Interface"]

maintainer = "Beno√Æt G."
license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/gordielachance/blender-focus-on-selected-gui"

blender_version_min = "4.2.0"

[permissions]
files = "Access to UI headers"
